[package]
name = "tor-client-ascii"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
tor-client-common.workspace = true
tor-protocol.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
minifb = { version = "0.28", default-features = false, features = ["x11"] }
font8x8 = "0.3"
