id = 5
name = "Reliquary"
size = [7,5,2]
chamber = true
gravity = [0,0,-1]
anchors = { "west" = [0,2,0], "east" = [6,2,0] }
places = [{ at = [3,2,0], name = "Reliquary" }]
portals = [{ at = [0,2,0], direction = "west", to = "4/east", height = 2 }]
items = [{ id = 100, at = [4,2,0], name = "dawn seal" }]
