[package]
name = "tor-client-hack"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
tor-client-common.workspace = true
tor-protocol.workspace = true
serde.workspace = true
toml = "1.1.6"

[dev-dependencies]
serde_json.workspace = true
tor-client-common.workspace = true
tor-protocol.workspace = true
