//! Integration tests for this crate, compiled as one binary so each build
//! links one test executable instead of one per file.

mod arena_evaluation;
mod background_save;
mod checkpoints;
mod combat_diagnostics;
mod command_boundary;
mod creature_authoring;
mod descriptions;
mod doors;
mod dungeon;
mod generated_regions;
mod generation_groups;
mod geometry;
mod history;
mod invariants;
mod items;
mod materials;
mod package_pin;
mod paired_stairs;
mod palettes;
mod performance_contracts;
mod performance_workloads;
mod physics;
mod place_hints;
mod process;
mod recovery_fixtures;
mod region_horizon;
mod region_preloading;
mod region_streaming;
mod scenario_packages;
mod streaming_websocket;
mod support;
mod travel;
mod websocket;
mod wire_client;
mod wizard;
mod wizard_websocket;
